esphome:
  name: esp-gti
  friendly_name: ESP-GTI

  on_boot:
    priority: 600
    then:
      - number.set:
          id: gti_power
          value: 0

##########################################################
# ESP32
##########################################################

esp32:
  board: esp32-c5-devkitc-1
  variant: esp32c5

  framework:
    type: esp-idf
    version: latest

##########################################################
# LOGGER
##########################################################

logger:
  level: INFO

##########################################################
# API / OTA
##########################################################

api:

ota:
  - platform: esphome

##########################################################
# WIFI
##########################################################

wifi:
  ap:
    ssid: "ESP-GTI Setup"
    password: "12345678"

  reboot_timeout: 0s
  power_save_mode: none

captive_portal:

##########################################################
# WEB SERVER
##########################################################

web_server:
  port: 80

##########################################################
# MCP4151 COMPONENT
##########################################################

external_components:
  - source:
      type: git
      url: https://github.com/codermarti/esphome
      ref: dev
    components: [mcp4151]

##########################################################
# SPI
##########################################################

spi:
  clk_pin: GPIO6
  mosi_pin: GPIO7

##########################################################
# MCP4151 OUTPUT
##########################################################

output:
  - platform: mcp4151
    id: gti_pot
    cs_pin: GPIO10

##########################################################
# GTI POWER CONTROL
##########################################################

number:
  - platform: template
    name: "GTI Level"
    id: gti_power

    min_value: 0
    max_value: 100
    step: 1

    unit_of_measurement: "%"

    optimistic: true
    restore_value: true
    initial_value: 0

    set_action:
      - lambda: |-

          float level =
            (100.0 - x) / 100.0;

          id(gti_pot).set_level(level);

          ESP_LOGI(
            "GTI",
            "Level %.0f%% -> MCP %.3f",
            x,
            level
          );

##########################################################
# STATUS
##########################################################

text_sensor:
  - platform: wifi_info

    ip_address:
      name: "ESP-GTI IP"

binary_sensor:
  - platform: status
    name: "ESP-GTI Online"
